# Generated by Django 3.2.20 on 2023-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashRecord',
            fields=[
                ('hash_record_pk', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('hash_value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'hash_record',
            },
        ),
    ]
